fix com.android.phone.MiuiPhoneApp: java.lang.IllegalArgumentException
 E AndroidRuntime: java.lang.RuntimeException: Unable to create
application com.android.phone.MiuiPhoneApp:
java.lang.IllegalArgumentException: column 'sub_state' does not exist